# GraphQL Configuration
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

# Datasource Configuration
datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/graphQLExample?autoReconnect=true&useSSL=false
  username: root
  password:

# Hibernate Configuration
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  hbm2ddl:
    auto: none
  showSql: true
  current:
    session:
      context:
        class: org.springframework.orm.hibernate5.SpringSessionContext

# H2 configuration
spring:
  h2:
    console:
      enabled: true
      path: /h2-console